GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
	"title": "title-test3",
	"author": "author-test3",
	"url": "url-test3",
	"likes": "5552"
}

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
	"url": "url-test2",
	"likes": "5552"
}

###

DELETE http://localhost:3001/api/blogs/5ec9a97348dc480901c31613

###

PUT http://localhost:3001/api/blogs/5ec02b37c931871a586abf24
content-type: application/json

{
	"likes": "1"
}

###

POST http://localhost:3001/api/users 
content-type: application/json

{
	"name": "asdff",
	"username": "asdff",
	"password": "asdf"
}

###

GET http://localhost:3001/api/users 